import type { SiteContent } from "@/types/content";

/**
 * Social handles, in one place because the footer and the order band both
 * need them and a second copy is a second thing to get wrong.
 *
 * `.example` is the IANA-reserved placeholder name, used for the same reason
 * the phone number and the WhatsApp number are unassigned: these must read
 * unmistakably as stand-ins and must not resolve to some real account that
 * would then be associated with a fictional brand. They are structurally
 * valid links — the pattern is demonstrated — that lead nowhere.
 */
const HANDLE = "nabat.example";

const social = {
  instagram: { label: "اینستاگرام", href: `https://instagram.com/${HANDLE}` },
  telegram: { label: "تلگرام", href: `https://t.me/${HANDLE}` },
};

/**
 * PLACEHOLDER CONTENT.
 *
 * The brand name, contact details and handles below are stand-ins so the
 * layout can be reviewed with realistic Persian text. Phone, WhatsApp, email
 * and address are deliberately non-functional. Nothing here asserts a fact
 * about a real business.
 */
export const site: SiteContent = {
  brand: {
    name: "نبات",
    latin: "NABAT",
    line: "نُه شیرینی، یک جعبه. زعفران، پسته، گلاب.",
  },

  seo: {
    title: "نبات — شیرینی و قند",
    titleTemplate: "%s — نبات",
    description:
      "نبات یک جعبهٔ نُه‌تایی از شیرینی و قند است؛ سه دسته، از قطاب و باقلوا تا نبات زعفرانی و پولکی. سفارش تلفنی و واتساپ.",
    /** Generated by `scripts/generate-og.mjs` — a PNG, not an SVG like the
     *  pattern plates, because no social crawler renders an SVG share card. */
    ogImage: {
      src: "/media/og-card.png",
      alt: "نشان نبات روی زمینهٔ نقش‌دار زعفرانی",
      width: 1200,
      height: 630,
    },
  },

  /**
   * Hrefs are written from the site root so the header works on every page —
   * a bare `#order` resolves against whatever page the header happens to be
   * rendered on, which is nothing at all outside the homepage. `next/link`
   * also applies the deployment base path to a root-relative href, so this is
   * the only form that survives a GitHub Pages project subpath.
   *
   * «سفارش» points at the homepage's order band rather than getting a route
   * of its own: the conversion is a phone call or a WhatsApp message, and a
   * page whose entire content is two links is a page that did not need to
   * exist.
   */
  nav: [
    { label: "جعبه", href: "/products/" },
    { label: "گالری", href: "/gallery/" },
    { label: "دربارهٔ نبات", href: "/about/" },
    { label: "سفارش", href: "/#order" },
  ],

  headerCta: { label: "سفارش", href: "/#order" },

  contact: {
    city: "تهران",
    phone: "۰۲۱ — ۰۰۰۰ ۰۰۰۰",
    phoneHref: "+982100000000",
    /**
     * WhatsApp number for click-to-chat, in Latin digits with no punctuation —
     * `wa.me` accepts nothing else, and Persian digits are not matched by `\d`,
     * which is the bug that produced empty `tel:` links on the first site in
     * this family.
     *
     * Deliberately unassigned. `wa.me` answers an unassigned number with "this
     * link is invalid" rather than opening a chat with a stranger, which is the
     * correct behaviour for a placeholder.
     */
    whatsapp: "989000000000",
    address: "تهران، خیابان نمونه، شمارهٔ ۰۰",
    hours: "هر روز، ۹ تا ۲۱",
    email: "salam@nabat.example",
    instagram: { handle: `@${HANDLE}`, href: social.instagram.href },
  },

  social: [social.instagram, social.telegram],

  /**
   * Empty on purpose, and the footer hides the row while it is.
   *
   * A privacy policy and terms of use are the one category of content where
   * inventing plausible text is actively harmful. Add real entries here when
   * real policies exist and the row comes back with no change to any
   * component.
   */
  legal: [],

  footer: {
    navHeading: "جعبه",
    contactHeading: "سفارش",
  },

  copyright: "© ۱۴۰۵ نبات — تمام حقوق محفوظ است.",
};
